### PR TITLE
add sam-tests/ to initially generated default .gitignore

### PR DESCRIPTION
**Pull request by PatMyron**
Credentials committed in `sam-tests/` in several `resource-providers` already:
[gamelift](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-gamelift/pull/9#discussion_r432213015)
[cloudwatch](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudwatch/pull/2/files/1afad8dd9d53ae5210c0624ee2a8ead7818993ae#diff-83d85f3c2f1785dcc53ab51e9abd2f2c)

Other language plugins as well:
[Python](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/97)
[Go](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/pull/144)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ammokhov** [comment]
> [aws-cloudformation/aws-cloudformation-resource-providers-gamelift#9 (comment)](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-gamelift/pull/9#discussion_r432213015)
> 
> https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudwatch/pull/2/files/1afad8dd9d53ae5210c0624ee2a8ead7818993ae#r409312986
> 
> Investigating if this needs to be added to the other language plugins as well:
> [Python](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/blob/master/python/rpdk/python/data/Python.gitignore)
> [Go](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/blob/master/python/rpdk/go/data/go.gitignore)
> 
> By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

the only issue with that is that folder name can be anything

**Comment by PatMyron** [comment]
> the only issue with that is that folder name can be anything

Is it `sam-tests/` by default?

Everyone still needs to install and configure [`git-secrets`](https://github.com/awslabs/git-secrets#installing-git-secrets) regardless:
```bash
brew install git-secrets
git secrets --register-aws --global
git secrets --install # in each repository
```

this is just meant to be another layer of protection for anyone who hasn't

**Comment by miparnisari** [comment]
> > Everyone still needs to install and configure [`git-secrets`](https://github.com/awslabs/git-secrets#installing-git-secrets) 

is this documented somewhere?

**Comment by rjlohan** [comment]
> > Everyone still needs to install and configure [`git-secrets`](https://github.com/awslabs/git-secrets#installing-git-secrets)
> 
> is this documented somewhere?

This is just a general best-practice for git workflows to prevent exactly this sort of problem. It's sourced from [here](https://github.com/awslabs/git-secrets)

**Comment by PatMyron** [comment]
> > Everyone still needs to install and configure [`git-secrets`](https://github.com/awslabs/git-secrets#installing-git-secrets)
> 
> is this documented somewhere?

[documented](https://w.amazon.com/bin/view/AWS21/Design/Uluru/Howto_GitHub/#HGit-Secrets) and called out [`git-secrets`](https://github.com/awslabs/git-secrets#installing-git-secrets) caveats: 

https://github.com/awslabs/git-secrets/pull/172/files
https://github.com/awslabs/git-secrets/pull/173/files

**Pull request merged**
