### PR TITLE
Revert "Log response payload for better troubleshooting (#320)"

### PR DESCRIPTION
**Pull request by wbingli**
This reverts commit 4bdae6ec8d27543fa0ca9a4d50515cdf325ad953.

*Issue #, if available:*

*Description of changes:* Revert the response payload logs.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by sungkkim — APPROVED** [review]

**Comment by wbingli** [comment]
The integration test is broken so far due to `cfn` command support module now. 

Looking to fix it.

**Review by jotompki — APPROVED** [review]

**Comment by jotompki** [comment]
https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/326/files to fix the integ

**Review by ammokhov — APPROVED** [review]

**Comment by wbingli** [comment]
> https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/326/files to fix the integ

That fix doesn't work. 


```
$ cfn init -vv -t AWS::Foo::Bar -a RESOURCE
Logging set up successfully
Running None: Namespace(artifact_type='RESOURCE', command=<function init at 0x7fc88596d378>, force=False, subparser_name=None, type_name='AWS::Foo::Bar', verbose=2, version=False)
Root directory: /tmp/tmp.5Ivhk6tjWz
Initializing new project
Loading project file '/tmp/tmp.5Ivhk6tjWz/.rpdk-config'
One language plugin found, defaulting to java
Language plugin: java
Init started
Enter a package name (empty for default 'software.amazon.foo.bar'): 
>> 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by wbingli** [comment]
A PR to fix the build: https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/337

**Pull request merged**
